#!/bin/bash

# Wrapper for `dtk dol diff` to locate the first diff in the dol.
# Usage: ./dol-diff [VERSION]
# If VERSION is not provided, it defaults to oot-j.

set -euo pipefail

VERSION=${1:-oot-j}
NAME=$(sed -n 's/^name: *//p' "config/$VERSION/config.yml")
ninja "build/$VERSION/$NAME.elf"
build/tools/dtk dol diff "config/$VERSION/config.yml" "build/$VERSION/$NAME.elf"
